[package]
name = "aruco"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["com"]

[dependencies.opencv]
version = "0.79.0"
features = ["highgui", "videoio", "objdetect"]

[dependencies]
com = { path = "com" }
tokio = { version = "1.28.0", features = ["full"] }